# Generated by Django 4.0.6 on 2022-07-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emplist_app', '0002_employees_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='user',
            new_name='dummy_user',
        ),
    ]
